spring.application.name=identity_service
server.port=8081
spring.datasource.url = jdbc:postgresql://localhost:5432/identity-service
spring.datasource.username=postgres
spring.datasource.password=thinh1234
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.signerKey=BpbYzjZCyoHbx8E8AvSPDFxsE0739IlW4YKWheQPHSnIDtl/3jZNcLiKonRqda2DQ1rr72U0EUZ0TksWFBLBzwaS

jwt.valid-duration=3600000

jwt.refreshable-duration=3600