spring.application.name=identity_service
server.port=8081
spring.datasource.url = jdbc:postgresql://localhost:5432/identity-service
spring.datasource.username=postgres
spring.datasource.password=thinh1234
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=thinh1234
logging.level.org.springframework.data.redis==DEBUG

jwt.signerKey=BpbYzjZCyoHbx8E8AvSPDFxsE0739IlW4YKWheQPHSnIDtl/3jZNcLiKonRqda2DQ1rr72U0EUZ0TksWFBLBzwaS

jwt.valid-duration=3600

jwt.refreshable-duration=36000

app.cookie.secure=false
app.cookie.same-site=Lax
app.cookie.max-age=604800