spring.application.name=api_gateway

server.port=8080

app.api-prefix=/api/v1

spring.cloud.gateway.server.webflux.routes[0].id=identity-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=${app.api-prefix}/auth/**